// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtoaqRe14m0_XNWTXSdahRvn_hxVbagik',
    appId: '1:247606092400:web:e5ad237150b1fb07210ab5',
    messagingSenderId: '247606092400',
    projectId: 'marvel-info-5a3e1',
    authDomain: 'marvel-info-5a3e1.firebaseapp.com',
    storageBucket: 'marvel-info-5a3e1.firebasestorage.app',
    measurementId: 'G-QMESZSS78Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKwuUijdKauUdUa5Gb9lACzJquv4MTKSg',
    appId: '1:247606092400:android:22cf895942c372e0210ab5',
    messagingSenderId: '247606092400',
    projectId: 'marvel-info-5a3e1',
    storageBucket: 'marvel-info-5a3e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2r-U_Tf-g_vlT_xfLtrC_K1xQsixLVYA',
    appId: '1:247606092400:ios:9e79968428c3f0c3210ab5',
    messagingSenderId: '247606092400',
    projectId: 'marvel-info-5a3e1',
    storageBucket: 'marvel-info-5a3e1.firebasestorage.app',
    iosBundleId: 'com.example.marvelInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2r-U_Tf-g_vlT_xfLtrC_K1xQsixLVYA',
    appId: '1:247606092400:ios:9e79968428c3f0c3210ab5',
    messagingSenderId: '247606092400',
    projectId: 'marvel-info-5a3e1',
    storageBucket: 'marvel-info-5a3e1.firebasestorage.app',
    iosBundleId: 'com.example.marvelInfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtoaqRe14m0_XNWTXSdahRvn_hxVbagik',
    appId: '1:247606092400:web:14ba58ebe52de379210ab5',
    messagingSenderId: '247606092400',
    projectId: 'marvel-info-5a3e1',
    authDomain: 'marvel-info-5a3e1.firebaseapp.com',
    storageBucket: 'marvel-info-5a3e1.firebasestorage.app',
    measurementId: 'G-6XD70HNYHR',
  );
}
